### ISSUE TITLE
Why does BLE use `&dyn`?

### ISSUE THREAD

**Issue by Frostie314159** [bjoernQ/bleps#37]
This is more a question than an issue, but is there a specific reason, why bleps doesn't use generics instead of a dynamic reference to an HCIConnection on the `BLE` struct?
If this has a specific reason, please let me know. 
The `BLE` struct is likely only instantiated once in the entire application and monomorphization will likely even reduce code size here.

**Comment by bjoernQ** [comment]
There is no particular reason for that. Feel free to file a PR
